"""novel-ledger-v3 控制流水线：由 v1 单文件 pipeline.py 按域拆分，行为等价。

稳定导入面是本包命名空间（from .pipeline import X）；子模块名为内部结构，勿直接引用。
"""
from __future__ import annotations

from __future__ import annotations
import contextlib
import os
import re
import time
from pathlib import Path
from typing import Any
from ... import __version__
from ...content.gates import (
    blocking_plot_findings,
    expected_delta_duplicate_warnings,
    collect_plot_findings,
    foreign_fragment_issues,
    plot_findings_issues,
    recheck_beat_anchor_blockers,
    validate_prose_anchors,
    validate_write_output,
    word_count_warnings,
)
from ...content.hierarchical_memory import rebuild_hierarchical_memory, update_hierarchical_memory
from ...content.narrative_contract import narrative_contract_view
from ...content.reviews import review_summary
from ...ledger.ledger import (
    coerce_due,
    commit_event,
    load_snapshot,
    max_event_chapter,
    read_events,
    read_json_line,
    rollback_ledger_to,
)
from ...content.pack import SCENE_CHARS, assemble_pack, inputs_fingerprint, scene_budget, select_character_profiles, word_targets
from ...content.style_check import check_style_hard, check_style_text, style_direction
from ...infra.store import (
    OUTLINE_MILESTONE_KINDS,
    PHASE_AWAIT_ACK,
    PHASE_AWAIT_ASSEMBLY,
    PHASE_AWAIT_DRAFT,
    PHASE_AWAIT_POLISH,
    PHASE_BLOCKED,
    PHASE_COMPLETE,
    PHASE_IDLE,
    PHASE_SUBMITTED,
    BookStore,
    _volume_key_number,
    _volume_label,
    beats_count_warning,
    outline_budget_for_volume,
    validate_knowledge_refs,
    volume_entry_for,
)
from ...infra.scale import COMPLETION_MIN_RATIO, ENDGAME_MIN_RATIO, derive_chapter_word_target, scale_contract_errors
from ...infra.story_map import plan_story_map_errors
from ...content.views import (
    make_assemble_view,
    make_draft_view,
    make_polish_view,
    render_assemble_brief,
)
from ...infra.util import (
    LedgerError,
    atomic_json,
    atomic_json_ordered,
    atomic_text,
    canonical_json,
    chinese_word_count,
    now_ts,
    ok,
    read_json,
    sha256_text,
    stable_read_json,
    stable_read_text,
)
from ._common import *  # noqa: F401,F403
from ._usage import *  # noqa: F401,F403
from ._dispatch import *  # noqa: F401,F403
from ._planning import *  # noqa: F401,F403
from ._audit import *  # noqa: F401,F403
from ._quality import *  # noqa: F401,F403
from ._submit import *  # noqa: F401,F403
from ._commitack import *  # noqa: F401,F403
from ._flow import *  # noqa: F401,F403
from ._status import *  # noqa: F401,F403

__all__ = [
    'ACK_QUOTE_MIN',
    'QUOTE_DISTRIBUTION_MIN_CHARS',
    'WORKER_PROMPT_PROTOCOL',
    'PLAN_CANDIDATES_SCHEMA',
    '_CANDIDATES_SKELETON',
    '_ACTION_ROLES',
    '_ACTION_CONTEXT_ISOLATION',
    '_ACTION_ROLE_CARDS',
    '_worker_brief',
    '_dispatched_job_id',
    '_is_dispatched_worker_session',
    '_with_execution_contract',
    '_ASSEMBLY_ONLY_ISSUES',
    '_PLOT_SELF_CHECK',
    '_style_gate_enabled',
    '_polish_disabled',
    '_style_structure_args',
    '_log_quality',
    '_corpus_style_fingerprint',
    '_require_active',
    'require_story_write_allowed',
    '_touch',
    '_runtime_identity',
    '_book_words_written',
    '_plan_extend_through',
    '_volume_watermark',
    'status',
    '_STATUS_CARD_KEYS',
    '_status_card',
    '_HEAD_TRANSITION_FIELDS',
    '_head_transition',
    'chapter_next',
    '_DISPATCH_CARD_KEYS',
    '_WORKER_CARD_KEYS',
    '_dispatch_card',
    '_chapter_next',
    '_usage_guard_action',
    '_consume_ack_usage_authorization',
    '_plan_extend_context',
    '_write_plan_extend_brief',
    'plan_rebudget',
    'plan_patch_chapter',
    '_candidate_fingerprint',
    'select_batch',
    '_begin_next',
    '_preserve_rework_text',
    '_refresh_stage_views',
    '_scene_budget',
    '_hooks_due_unplanned',
    'hooks_schedule_gaps',
    'overdue_hooks_undeclared',
    '_draft_action',
    '_polish_action',
    '_assembly_action',
    '_one_pass_expansion_hint',
    '_word_gate_result',
    'stage_draft_submit',
    'stage_polish_submit',
    '_style_metrics_gate_failed',
    '_polish_anchor_gate_failed',
    '_quote_requirements',
    '_ack_hint',
    '_quotes_all_in_first_half',
    '_ack_action',
    '_submission_review',
    '_dateline_warnings',
    'precheck_prose',
    'check_submit_output',
    'submit_output',
    '_attach_prose_hash',
    '_stale_plot_self_check',
    '_close_rechecked_findings',
    '_reassemble_if_stale',
    '_gate_fail',
    '_rewrite_recovery',
    '_plot_self_check_fail',
    '_commit',
    '_resumable_commit',
    '_commit_tail',
    '_validated_read_quotes',
    'ack_patched_chapter',
    'ack_read',
    '_reopen_p0',
    '_reopen_chapter',
    '_discard_committed_chapter',
    'retry_authorize',
    '_unresolved_long_term_commitments',
    'book_complete',
    'book_close_early',
    'book_reopen',
    '_merge_voice_memory',
    '_VOICE_NOTE_DROP_HINT',
    '_append_voice_concept',
    '_normalize_usage_sample',
    '_append_usage',
    '_find_usage_request',
    '_find_usage_void',
    'record_usage',
    'void_usage',
    'authorize_usage_resume',
    '_REWORK_EVENTS',
    '_quality_summary',
    '_content_numeric_audit',
    'reconcile_book',
    'calibrate_book',
    '_derived_name_drift',
    'audit_book',
    '_PACING_FLAT_THRESHOLD',
    '_TERMINAL_DEBT_STATUSES',
    '_VOLUME_REPETITION_OVERLAP',
    '_pacing_flat_run',
    '_shingles',
    '_cross_volume_repetition',
    '_irreversible_conditions',
    '_glossary_misuse',
    '_glossary_coverage',
    '_canon_source_drift',
    '_canon_drift',
    '_outline_volume_entry',
    '_act_volume_refs',
    '_outline_warnings',
    '_creative_advisory',
    '_outline_conformance',
    '_USAGE_DETAIL_WINDOW',
    '_usage_summary',
    '_quant_coverage_warnings',
    'validate_plan',
    'resync_baseline',
    '_restamp_canon_fingerprint',
    'audit_hooks',
    'close_hook',
    'defer_hook',
    'set_world_spine',
    'rename_relation',
    'close_relation',
    'merge_hook',
    'patch_prose',
    'rework_patch',
]
