"""Choice-driven book hatching assembly and initialization.

Turns a validated guided-v3 choice manifest into complete,
coherent novel assets (intent.md, outline.md, canon cards, chapters.json)
and initializes the book project so chapter next can run immediately.
"""

from __future__ import annotations

import copy
import json
import re
from pathlib import Path
from typing import Any

from ..content.extract import extract_cards
from ..content.narrative_contract import (NARRATIVE_CONTRACT_SCHEMA,
    narrative_contract_source_baselines, validate_narrative_contract)
from ..infra.volume_outline import (VOLUME_OUTLINE_SCHEMA, outline_han_count,
    sign_volume_outline_contract, volume_outline_errors)
from ..infra.scale import chapter_word_target_for_band, expected_total_chapters
from ..infra.story_map import PLAN_SCHEMA, story_map_errors
from ..infra.store import BookStore, DEFAULT_CONFIG, beats_count_warning, validate_knowledge_refs
from ..infra.util import LedgerError, atomic_text, ok
from ..voice.voice_manual import build_voice_profile, resolve_voice_id
from .bootstrap import copy_background_canon, init_project, resolve_background


def _hatch_chapter_target() -> int:
    """Sign the chapter aim generated by the project's default writing band."""
    return chapter_word_target_for_band(DEFAULT_CONFIG["word_band"])


def _get_protagonist(manifest: dict[str, Any]) -> str:
    protagonist = str(manifest.get("protagonist") or "").strip()
    if not protagonist:
        step2 = manifest.get("step2_protagonist")
        if isinstance(step2, dict):
            protagonist = str(step2.get("name") or "").strip()
    return protagonist


# 反套路主角名：模型起名高度趋同——潇洒姓×玄乎单字几乎覆盖 AI 产出的
# 两字主角名（叶辰/林轩/苏尘/沈夜/楚枫这一挂），读者一眼批量脸。advisory 只警不拦，
# 作者坚持以作者为准；纪律正文见 hatch-wizard 门 3（姓氏贴世界与阶层、俗字/双字名
# 优先、称呼链一次想好、口语测试）。
_CLICHE_SURNAMES = frozenset("叶林萧楚顾沈陆苏秦")
_CLICHE_GIVEN_CHARS = frozenset("辰尘轩言夜寒渊冥烬煜珩枫炎离策野绝")


def protagonist_name_cliche_warnings(name: str) -> list[dict[str, str]]:
    """高频 AI 套路主角名识别（heuristic，advisory）。

    两字名且姓与名单字各落池中才警；三字名（行辈字/俗字/双字名）天然更"真人"，不警。
    """
    cleaned = (name or "").strip()
    if len(cleaned) != 2:
        return []
    if cleaned[0] in _CLICHE_SURNAMES and cleaned[1] in _CLICHE_GIVEN_CHARS:
        return [
            {
                "code": "protagonist_name_cliche",
                "hint": (
                    "高频 AI 套路名（潇洒姓×玄乎单字）：模型生成的两字主角名高度趋同，"
                    "读者一眼批量脸。按 hatch-wizard 门 3 反套路命名纪律换：姓氏贴世界与阶层、"
                    "俗字/双字名更真人、称呼链（全名→日常称呼→诨名）一次想好、口语测试三遍。"
                    "advisory：作者坚持以作者为准。"
                ),
            }
        ]
    return []


_MISSING = object()
_HATCH_V3_SCHEMA = "novel-ledger.hatch.v3"
_SECTION_MODES = {"present", "none", "unresolved"}
_GUIDED_DECISION_IDS = (
    "reader_promise",
    "plot_architecture",
    "protagonist_engine",
    "core_relationships",
    "world_opposition",
    "story_mechanism",
    "main_arc",
    "scale",
    "voice_style",
)
_LEGACY_GUIDED_DECISION_IDS = (*_GUIDED_DECISION_IDS[:-2], "scale_voice")
_EXTRA_DECISION_ID = re.compile(r"extra_[a-z][a-z0-9_]*\Z")
_NONE_ALLOWED_DECISIONS = {"core_relationships", "story_mechanism"}
_DECISION_SOURCES = {"candidate", "custom", "author_supplied", "default", "none"}
_CN_SECTION_NUMBERS = ("〇", "一", "二", "三", "四", "五", "六", "七", "八", "九", "十", "十一", "十二")

# 视角结构与平台尺度：
# 两者都是 manifest 可选字段——不声明即按默认假设（单视角限知 + 红线自由文本）合法，
# 向导 v3 起在门 8 内出卡，作者声明后落 intent 并随 pack 渲染进 writing_brief 定位段。
# 枚举与渲染函数住在 content/pack.py（分层守卫：领域层不得反向依赖 control）。
from ..content.pack import (  # noqa: E402 — 放在常量区后，紧邻其唯一消费者
    FENCE_TIERS,
    POV_GRANULARITIES,
    POV_STRUCTURES,
    render_content_fence,
    render_narrative_pov,
    select_character_profiles,
)


def _object(value: Any) -> dict[str, Any]:
    return value if isinstance(value, dict) else {}


def _text(value: Any) -> str:
    return value.strip() if isinstance(value, str) else ""


def _schema_version(manifest: dict[str, Any]) -> int:
    return 3 if manifest.get("schema") == _HATCH_V3_SCHEMA else 0


def _mode(raw: dict[str, Any]) -> str:
    if not raw:
        return "unresolved"
    value = raw.get("mode")
    if value is None:
        return "present"
    mode = _text(value).lower()
    return mode if mode in _SECTION_MODES else "invalid"


def _section_heading(index: int, title: str) -> str:
    label = _CN_SECTION_NUMBERS[index] if index < len(_CN_SECTION_NUMBERS) else str(index)
    return f"## {label}、{title}"


def _get_main_plotline(manifest: dict[str, Any]) -> dict[str, Any]:
    """Read the canonical v3 main plotline shape without aliases."""
    raw = manifest.get("main_plotline")
    if not isinstance(raw, dict):
        return {"mode": "invalid", "progression_arc": [], "_shape_valid": False}

    raw_arc = raw.get("progression_arc")
    arc_shape_valid = isinstance(raw_arc, list)
    progression_arc: list[dict[str, str]] = []
    if isinstance(raw_arc, list):
        for item in raw_arc:
            if not isinstance(item, dict):
                arc_shape_valid = False
                continue
            progression_arc.append({
                "stage": _text(item.get("stage")),
                "goal": _text(item.get("goal")),
            })
    return {
        "mode": _mode(raw),
        "core_quest": _text(raw.get("core_quest")),
        "driving_force": _text(raw.get("driving_force")),
        "progression_arc": progression_arc,
        "volume1_hook": _text(raw.get("volume1_hook")),
        "endgame_condition": _text(raw.get("endgame_condition")),
        "_shape_valid": arc_shape_valid,
    }


def _get_cheat_constraint(manifest: dict[str, Any]) -> dict[str, Any]:
    """Read the canonical v3 story mechanism shape without aliases."""
    raw = manifest.get("story_mechanism")
    if not isinstance(raw, dict):
        return {"mode": "invalid", "_shape_valid": False}
    return {
        "mode": _mode(raw),
        "name": _text(raw.get("name")),
        "mechanism": _text(raw.get("mechanism")),
        "cost_and_backlash": _text(raw.get("cost_and_backlash")),
        "limitations": _text(raw.get("limitations")),
        "workaround": _text(raw.get("workaround")),
        "_shape_valid": True,
    }


def _get_sustenance_craft(manifest: dict[str, Any]) -> dict[str, Any]:
    """Read the canonical v3 material-life shape without aliases."""
    raw = manifest.get("material_life")
    if not isinstance(raw, dict):
        return {"mode": "invalid", "_shape_valid": False}
    return {
        "mode": _mode(raw),
        "profession": _text(raw.get("profession")),
        "income_loop": _text(raw.get("income_loop")),
        "social_network": _text(raw.get("social_network")),
        "cover_persona": _text(raw.get("cover_persona")),
        "_shape_valid": True,
    }


def _get_world_mystery(manifest: dict[str, Any]) -> dict[str, Any]:
    """Read the canonical v3 long-arc shape without aliases."""
    raw = manifest.get("long_arc_question")
    if not isinstance(raw, dict):
        return {"mode": "invalid", "decryption_ladder": [], "_shape_valid": False}

    raw_ladder = raw.get("decryption_ladder", [])
    ladder_shape_valid = isinstance(raw_ladder, list)
    decryption_ladder: list[dict[str, str]] = []
    if isinstance(raw_ladder, list):
        for item in raw_ladder:
            if not isinstance(item, dict):
                ladder_shape_valid = False
                continue
            decryption_ladder.append({
                "stage": _text(item.get("stage")),
                "truth": _text(item.get("truth")),
            })
    return {
        "mode": _mode(raw),
        "core_mystery": _text(raw.get("core_mystery")),
        "surface_illusion": _text(raw.get("surface_illusion")),
        "decryption_ladder": decryption_ladder,
        "_shape_valid": ladder_shape_valid,
    }


def _v3_error(field: str, message: str) -> None:
    raise LedgerError("invalid_hatch_v3", f"{field}: {message}", {"field": field})


def _normalized_long_term_commitments(step4: dict[str, Any]) -> list[dict[str, Any]]:
    """Give book-level promises stable IDs shared by the plan and rendered outline."""
    raw = step4.get("long_term_commitments")
    if raw is None:
        return []
    if not isinstance(raw, list):
        _v3_error("step4_outline.long_term_commitments", "must be a list")

    spine = _object(step4.get("event_spine"))
    subplots = spine.get("subplots")
    arc_ids = {
        _text(owner.get("id"))
        for owner in [spine.get("mainline"), *(subplots if isinstance(subplots, list) else [])]
        if isinstance(owner, dict) and _text(owner.get("id"))
    }
    normalized: list[dict[str, Any]] = []
    seen_ids: set[str] = set()
    for index, item in enumerate(raw, 1):
        field = f"step4_outline.long_term_commitments[{index - 1}]"
        if not isinstance(item, dict):
            _v3_error(field, "must be an object")
        supplied_id = item.get("id")
        if supplied_id is None or (isinstance(supplied_id, str) and not supplied_id.strip()):
            ident = f"commitment-{index:04d}"
        elif isinstance(supplied_id, str):
            ident = supplied_id.strip()
        else:
            _v3_error(f"{field}.id", "must be a non-empty string when supplied")
        if ident in seen_ids:
            _v3_error(f"{field}.id", f"duplicate commitment id: {ident}")
        seen_ids.add(ident)

        promise = _text(item.get("promise"))
        if not promise:
            _v3_error(f"{field}.promise", "must be a non-empty string")
        planted = item.get("planted_volume")
        resolved = item.get("resolved_volume")
        for name, value in (("planted_volume", planted), ("resolved_volume", resolved)):
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                _v3_error(f"{field}.{name}", "must be a positive integer")
        if planted > resolved:
            _v3_error(field, "planted_volume must not exceed resolved_volume")

        description = item.get("description", "")
        if not isinstance(description, str):
            _v3_error(f"{field}.description", "must be a string")
        entry: dict[str, Any] = {
            "id": ident,
            "promise": promise,
            "planted_volume": planted,
            "resolved_volume": resolved,
            "description": description.strip(),
        }
        if "arc_ref" in item:
            arc_ref = _text(item["arc_ref"])
            if arc_ref not in arc_ids:
                _v3_error(f"{field}.arc_ref", "must reference an event_spine mainline or subplot id")
            entry["arc_ref"] = arc_ref
        for name in ("seed_use", "final_condition"):
            if name in item:
                value = item[name]
                if not isinstance(value, str):
                    _v3_error(f"{field}.{name}", "must be a string")
                entry[name] = value.strip()
        normalized.append(entry)
    return normalized


def _validate_text_list(field: str, value: Any, *, minimum: int = 1, maximum: int | None = None) -> list[str]:
    if not isinstance(value, list):
        _v3_error(field, "must be a list")
    cleaned = [_text(item) for item in value]
    if any(not item for item in cleaned):
        _v3_error(field, "must contain only non-empty strings")
    if len(cleaned) < minimum:
        _v3_error(field, f"must contain at least {minimum} item(s)")
    if maximum is not None and len(cleaned) > maximum:
        _v3_error(field, f"must contain at most {maximum} item(s)")
    if len(set(cleaned)) != len(cleaned):
        _v3_error(field, "must not contain duplicates")
    return cleaned


def _validate_guided_decisions(manifest: dict[str, Any]) -> dict[str, dict[str, Any]]:
    wizard = _object(manifest.get("wizard"))
    if wizard.get("mode") != "guided":
        _v3_error("wizard.mode", "must be guided")
    if wizard.get("status") != "confirmed":
        raise LedgerError(
            "hatch_unresolved",
            "guided hatch is not fully confirmed",
            {"field": "wizard.status"},
        )
    if wizard.get("final_confirmation") is not True:
        raise LedgerError(
            "hatch_unresolved",
            "guided hatch requires one final start confirmation",
            {"field": "wizard.final_confirmation"},
        )

    raw_decisions = wizard.get("decisions")
    if not isinstance(raw_decisions, list):
        _v3_error("wizard.decisions", "must be a list")
    raw_ids = [_text(item.get("id")) if isinstance(item, dict) else "" for item in raw_decisions]
    if raw_ids == list(_LEGACY_GUIDED_DECISION_IDS):
        # Already confirmed v3 manifests used one combined scale/voice gate.
        decision_ids = _LEGACY_GUIDED_DECISION_IDS
    else:
        # New manifests retain every base gate in order. Additional questions may
        # follow any base gate when their independent reason is recorded.
        decision_ids = _GUIDED_DECISION_IDS
        base_index = 0
        latest_base = ""
        extra_ids: set[str] = set()
        for index, raw in enumerate(raw_decisions):
            field = f"wizard.decisions[{index}]"
            if not isinstance(raw, dict):
                _v3_error(field, "must be an object")
            decision_id = raw_ids[index]
            if base_index < len(decision_ids) and decision_id == decision_ids[base_index]:
                latest_base = decision_id
                base_index += 1
            elif _EXTRA_DECISION_ID.fullmatch(decision_id):
                if not latest_base:
                    _v3_error(f"{field}.id", "extra decisions must follow a base decision")
                if decision_id in extra_ids:
                    _v3_error(f"{field}.id", "must be unique")
                extra_ids.add(decision_id)
                if _text(raw.get("after")) != latest_base:
                    _v3_error(f"{field}.after", "must name the nearest preceding base decision")
                if not _text(raw.get("reason")):
                    _v3_error(f"{field}.reason", "must explain why this separate decision is needed")
            else:
                _v3_error(
                    f"{field}.id",
                    "must follow the base dependency order or use a unique extra_<slug> id",
                )
        if base_index != len(decision_ids):
            _v3_error(
                "wizard.decisions",
                "must include all base decisions in order: " + " -> ".join(decision_ids),
            )
    decisions: dict[str, dict[str, Any]] = {}
    axes: set[str] = set()
    for index, raw in enumerate(raw_decisions):
        field = f"wizard.decisions[{index}]"
        if not isinstance(raw, dict):
            _v3_error(field, "must be an object")
        decision_id = _text(raw.get("id"))
        is_extra = bool(_EXTRA_DECISION_ID.fullmatch(decision_id))
        if decision_id not in decision_ids and not is_extra:
            _v3_error(f"{field}.id", "is unknown")
        if decision_id in decisions:
            _v3_error(f"{field}.id", "must be unique")

        status = _text(raw.get("status"))
        if is_extra and not isinstance(raw.get("none_allowed"), bool):
            _v3_error(f"{field}.none_allowed", "must be a boolean")
        none_allowed = raw["none_allowed"] if is_extra else decision_id in _NONE_ALLOWED_DECISIONS
        expected_statuses = {"confirmed", "none"} if none_allowed else {"confirmed"}
        if status not in expected_statuses:
            if status in {"", "unresolved", "provisional"}:
                raise LedgerError(
                    "hatch_unresolved",
                    f"guided hatch decision is not confirmed: {decision_id}",
                    {"field": field, "decision_id": decision_id},
                )
            _v3_error(f"{field}.status", f"must be one of {sorted(expected_statuses)}")

        cardinality = _text(raw.get("cardinality"))
        if cardinality != "one":
            _v3_error(f"{field}.cardinality", "guided v3 uses one-path choices; must be one")
        if raw.get("custom_allowed") is not True:
            _v3_error(f"{field}.custom_allowed", "must be true")
        if bool(raw.get("none_allowed")) != none_allowed:
            _v3_error(f"{field}.none_allowed", f"must be {str(none_allowed).lower()}")

        source = _text(raw.get("source"))
        if source not in _DECISION_SOURCES:
            _v3_error(f"{field}.source", "is invalid")
        if status == "none" and source != "none":
            _v3_error(f"{field}.source", "must be none when status is none")
        if status == "confirmed" and source == "none":
            _v3_error(f"{field}.source", "cannot be none when status is confirmed")
        axis = _text(raw.get("axis"))
        if not axis:
            _v3_error(f"{field}.axis", "must name the single decision axis")
        if axis in axes:
            _v3_error(f"{field}.axis", "must be distinct from every other decision axis")
        axes.add(axis)
        if not _text(raw.get("summary")):
            _v3_error(f"{field}.summary", "must record the selected result")

        options = raw.get("options", [])
        if source == "author_supplied" and options in (None, []):
            options = []
        elif not isinstance(options, list) or not 2 <= len(options) <= 3:
            _v3_error(f"{field}.options", "must contain 2-3 comparable candidates")

        option_ids: list[str] = []
        for option_index, option in enumerate(options):
            option_field = f"{field}.options[{option_index}]"
            if not isinstance(option, dict):
                _v3_error(option_field, "must be an object")
            option_id = _text(option.get("id"))
            if not option_id:
                _v3_error(f"{option_field}.id", "is required")
            option_ids.append(option_id)
            for key in ("label", "outcome", "benefit", "cost", "risk"):
                if not _text(option.get(key)):
                    _v3_error(option_field, f"missing required field: {key}")
            if decision_id == "voice_style":
                option_voice_id = _text(option.get("voice_id"))
                if not option_voice_id:
                    _v3_error(f"{option_field}.voice_id", "must identify an available voice")
                resolve_voice_id(option_voice_id)
        if decision_id == "voice_style" and len({_text(option["voice_id"]) for option in options}) != len(options):
            _v3_error(f"{field}.options", "candidate voice_ids must be distinct")
        if len(set(option_ids)) != len(option_ids):
            _v3_error(f"{field}.options", "candidate ids must be unique")
        if option_ids and option_ids != list("ABC"[:len(option_ids)]):
            _v3_error(f"{field}.options", "candidate ids must be A/B or A/B/C in display order")
        for key in ("label", "outcome"):
            values = [_text(option.get(key)).casefold() for option in options]
            if len(set(values)) != len(values):
                _v3_error(f"{field}.options", f"candidate {key}s must be meaningfully distinct")

        selected = raw.get("selected", [])
        if not isinstance(selected, list) or any(not _text(item) for item in selected):
            _v3_error(f"{field}.selected", "must be a list of non-empty ids")
        selected_ids = [_text(item) for item in selected]
        if len(set(selected_ids)) != len(selected_ids):
            _v3_error(f"{field}.selected", "must not contain duplicates")
        if source in {"candidate", "default"}:
            if not selected_ids or any(item not in option_ids for item in selected_ids):
                _v3_error(f"{field}.selected", "must reference presented candidate ids")
            if cardinality == "one" and len(selected_ids) != 1:
                _v3_error(f"{field}.selected", "must contain exactly one id")
        elif source == "none":
            if selected_ids not in ([], ["none"]):
                _v3_error(f"{field}.selected", "must be empty or [none]")
        elif source in {"custom", "author_supplied"} and selected_ids:
            _v3_error(f"{field}.selected", "must be empty for custom or author-supplied values")

        recommended_id = _text(raw.get("recommended_id"))
        if recommended_id:
            if recommended_id not in option_ids:
                _v3_error(f"{field}.recommended_id", "must reference a candidate id")
            if not _text(raw.get("recommendation_reason")):
                _v3_error(f"{field}.recommendation_reason", "is required when recommending an option")
        if source == "default" and (not recommended_id or selected_ids != [recommended_id]):
            _v3_error(field, "default source must select the explicitly recommended candidate")
        if decision_id == "voice_style":
            voice_id = _text(raw.get("voice_id"))
            if not voice_id:
                _v3_error(f"{field}.voice_id", "must record the chosen voice id")
            resolve_voice_id(voice_id)
            if voice_id != _text(manifest.get("voice")):
                _v3_error(f"{field}.voice_id", "must match top-level voice")
            if source in {"candidate", "default"}:
                selected_voice_id = next(
                    _text(option["voice_id"])
                    for option in options
                    if _text(option.get("id")) == selected_ids[0]
                )
                if voice_id != selected_voice_id:
                    _v3_error(f"{field}.voice_id", "must match the selected candidate voice_id")
        decisions[decision_id] = raw

    missing = [item for item in decision_ids if item not in decisions]
    if missing:
        raise LedgerError(
            "hatch_unresolved",
            "guided hatch decisions are incomplete",
            {"field": "wizard.decisions", "missing": missing},
        )
    return decisions


def _validate_v3_mode_section(
    manifest: dict[str, Any],
    field: str,
    normalized: dict[str, Any],
    required: tuple[str, ...],
) -> None:
    raw = manifest.get(field, _MISSING)
    if not isinstance(raw, dict) or "mode" not in raw:
        raise LedgerError(
            "hatch_unresolved",
            f"guided hatch requires an explicit present/none decision for {field}",
            {"field": field},
        )
    mode = normalized.get("mode")
    if mode not in {"present", "none"}:
        if mode == "unresolved":
            raise LedgerError("hatch_unresolved", f"{field} is unresolved", {"field": field})
        _v3_error(field, "mode must be present or none")
    if mode == "none":
        payload = [key for key, value in raw.items() if key != "mode" and value not in (None, "", [], {})]
        if payload:
            _v3_error(field, "mode none must not carry story content: " + ", ".join(sorted(payload)))
        return
    if not normalized.get("_shape_valid", True):
        _v3_error(field, "must use the documented object shape")
    # v3 is a single canonical contract: aliases from older manifests are not
    # accepted, even if the renderer could otherwise normalize them.
    missing = [key for key in required if not _text(raw.get(key))]
    if missing:
        _v3_error(field, "missing required fields: " + ", ".join(missing))


def _validate_relationship_structure(manifest: dict[str, Any]) -> dict[str, Any]:
    raw = manifest.get("relationship_structure")
    if not isinstance(raw, dict) or "mode" not in raw:
        raise LedgerError(
            "hatch_unresolved",
            "guided hatch requires an explicit relationship_structure present/none decision",
            {"field": "relationship_structure"},
        )
    mode = _text(raw.get("mode")).lower()
    if mode == "none":
        payload = [key for key, value in raw.items() if key != "mode" and value not in (None, "", [], {})]
        if payload:
            _v3_error("relationship_structure", "mode none must not carry relationship content")
        return raw
    if mode != "present":
        _v3_error("relationship_structure.mode", "must be present or none")
    if not _text(raw.get("pattern")):
        _v3_error("relationship_structure.pattern", "is required")
    relationships = raw.get("relationships")
    if not isinstance(relationships, list) or not relationships:
        _v3_error("relationship_structure.relationships", "must contain at least one relationship")
    for index, item in enumerate(relationships):
        field = f"relationship_structure.relationships[{index}]"
        if not isinstance(item, dict):
            _v3_error(field, "must be an object")
        for key in ("name", "relationship_type", "independent_goal", "boundary", "change_arc"):
            if not _text(item.get(key)):
                _v3_error(field, f"missing required field: {key}")
        _validate_text_list(f"{field}.participants", item.get("participants"), minimum=2)
    return raw


def _initial_phase(step4: dict[str, Any], step5: dict[str, Any], chapter_end: int = 3) -> dict[str, Any]:
    """Build the signed opening phase against all four event-spine layers."""
    acts = step4.get("acts") or []
    stage = _text(acts[0].get("name")) if acts and isinstance(acts[0], dict) else ""
    spine = _object(step4.get("event_spine"))
    mainline = _object(spine.get("mainline"))

    def first_event_id(owner: dict[str, Any]) -> str:
        return next(
            (
                _text(event.get("id"))
                for event in (owner.get("events") or [])
                if isinstance(event, dict) and _text(event.get("stage")) == stage
            ),
            "",
        )

    subplot_refs = [
        event_id
        for subplot in (spine.get("subplots") or [])
        if isinstance(subplot, dict)
        for event_id in [first_event_id(subplot)]
        if event_id
    ][:3]
    timeline_refs = [
        event_id
        for clock in (spine.get("timelines") or [])
        if isinstance(clock, dict)
        for event_id in [first_event_id(clock)]
        if event_id
    ][:3]
    selected_refs = [first_event_id(mainline), *subplot_refs, *timeline_refs]
    event_changes: dict[str, str] = {}
    for owner in [mainline, *(item for item in (spine.get("subplots") or []) if isinstance(item, dict))]:
        for event in owner.get("events") or []:
            if isinstance(event, dict) and _text(event.get("id")) in selected_refs:
                event_changes[_text(event.get("id"))] = _text(event.get("change"))
    for owner in (spine.get("timelines") or []):
        if not isinstance(owner, dict):
            continue
        for event in owner.get("events") or []:
            if isinstance(event, dict) and _text(event.get("id")) in selected_refs:
                event_changes[_text(event.get("id"))] = (
                    f"{_text(event.get('event'))}；截止条件为{_text(event.get('deadline'))}；"
                    f"若错失则{_text(event.get('consequence'))}"
                )
    tension = next(
        (
            item for item in (spine.get("tension_curve") or [])
            if isinstance(item, dict) and _text(item.get("stage")) == stage
        ),
        {},
    )
    return {
        "id": "phase-opening",
        "name": "开篇阶段",
        "story_stage": stage,
        "chapter_start": 1,
        "chapter_end": chapter_end,
        "objective": _text(step5.get("spine")),
        "climax": _text(step5.get("climax")),
        "mainline_event_ref": first_event_id(mainline),
        "subplot_event_refs": subplot_refs,
        "timeline_event_refs": timeline_refs,
        "tension_stage": stage,
        "entry_state": f"阶段开始时，{_text(step5.get('spine'))}尚未完成",
        "exit_state": _text(step5.get("climax")),
        "event_changes": event_changes,
        "tension_change": (
            f"由{_text(tension.get('pressure'))}施压，经{_text(tension.get('turn'))}转折，"
            f"兑现为{_text(tension.get('payoff'))}"
        ),
    }


def _opening_chapter_refs(
    step4: dict[str, Any],
    chapter_index: int,
    opening_phase: dict[str, Any],
) -> tuple[list[str], list[str]]:
    """Distribute opening phase owners so the seed batch covers every selected layer."""
    spine = _object(step4.get("event_spine"))
    event_owner: dict[str, str] = {}
    mainline = _object(spine.get("mainline"))
    for owner in [mainline, *(item for item in (spine.get("subplots") or []) if isinstance(item, dict))]:
        for event in owner.get("events") or []:
            if isinstance(event, dict):
                event_owner[_text(event.get("id"))] = _text(owner.get("id"))
    for owner in (spine.get("timelines") or []):
        if not isinstance(owner, dict):
            continue
        for event in owner.get("events") or []:
            if isinstance(event, dict):
                event_owner[_text(event.get("id"))] = _text(owner.get("id"))
    main_owner = event_owner.get(_text(opening_phase.get("mainline_event_ref")), "")
    subplot_owners = [event_owner.get(_text(ref), "") for ref in opening_phase.get("subplot_event_refs") or []]
    timeline_owners = [event_owner.get(_text(ref), "") for ref in opening_phase.get("timeline_event_refs") or []]
    thread_refs = [main_owner] if main_owner else []
    if subplot_owners:
        subplot_owner = subplot_owners[chapter_index % len(subplot_owners)]
        if subplot_owner:
            thread_refs.append(subplot_owner)
    clock_refs = []
    if timeline_owners:
        clock_owner = timeline_owners[chapter_index % len(timeline_owners)]
        if clock_owner:
            clock_refs.append(clock_owner)
    return thread_refs, clock_refs


def _validate_v3_contract(manifest: dict[str, Any]) -> None:
    decisions = _validate_guided_decisions(manifest)
    if not _text(manifest.get("title")):
        _v3_error("title", "must be a non-empty string")
    if not _text(manifest.get("voice")):
        _v3_error("voice", "must record the selected voice id")
    resolve_voice_id(_text(manifest["voice"]))
    background = manifest.get("background")
    if background is not None:
        if not _text(background):
            _v3_error("background", "must be a non-empty preset id when present")
        resolve_background(_text(background))
    book_words = manifest.get("book_words")
    if isinstance(book_words, bool) or not isinstance(book_words, int) or book_words <= 0:
        _v3_error("book_words", "must be a positive integer")

    step1 = _object(manifest.get("step1_hook"))
    _validate_text_list("step1_hook.genre_tags", step1.get("genre_tags"), minimum=1, maximum=4)
    for key in ("concept", "target_audience", "selling_points", "narrative_tone", "plot_architecture"):
        if not _text(step1.get(key)):
            _v3_error("step1_hook", f"missing required field: {key}")

    step2 = _object(manifest.get("step2_protagonist"))
    for key in ("name", "initial_status", "desire_surface", "desire_deep", "persona", "skillset"):
        if not _text(step2.get(key)):
            _v3_error("step2_protagonist", f"missing required field: {key}")
    if not (_text(step2.get("fatal_wound")) or _text(step2.get("core_pressure"))):
        _v3_error("step2_protagonist", "fatal_wound or core_pressure is required")
    if not (_text(step2.get("flaw")) or _text(step2.get("limitation"))):
        _v3_error("step2_protagonist", "flaw or limitation is required")
    if _get_protagonist(manifest) != _text(step2.get("name")):
        _v3_error("protagonist", "must match step2_protagonist.name")

    raw_profiles = manifest.get("character_profiles")
    if raw_profiles is not None:
        if not isinstance(raw_profiles, dict):
            _v3_error("character_profiles", "must be an object keyed by canonical character name")
        for name, record in raw_profiles.items():
            if not isinstance(name, str) or not name.strip():
                _v3_error("character_profiles", "character names must be non-empty strings")
            try:
                select_character_profiles({name: record}, [name])
            except LedgerError as exc:
                _v3_error(f"character_profiles.{name}", exc.message)

    relationship = _validate_relationship_structure(manifest)
    relationship_decision = decisions["core_relationships"]
    if (_text(relationship.get("mode")).lower() == "none") != (relationship_decision.get("status") == "none"):
        _v3_error("relationship_structure", "must match the core_relationships decision")

    mechanism = _get_cheat_constraint(manifest)
    _validate_v3_mode_section(
        manifest,
        "story_mechanism",
        mechanism,
        ("name", "mechanism", "cost_and_backlash", "limitations", "workaround"),
    )
    mechanism_decision = decisions["story_mechanism"]
    if (mechanism.get("mode") == "none") != (mechanism_decision.get("status") == "none"):
        _v3_error("story_mechanism", "must match the story_mechanism decision")
    _validate_v3_mode_section(
        manifest,
        "material_life",
        _get_sustenance_craft(manifest),
        ("profession", "income_loop", "social_network"),
    )
    _validate_v3_mode_section(
        manifest,
        "long_arc_question",
        _get_world_mystery(manifest),
        ("core_mystery", "surface_illusion"),
    )

    plotline = _get_main_plotline(manifest)
    if not isinstance(manifest.get("main_plotline"), dict) or plotline.get("mode") != "present":
        _v3_error("main_plotline", "must be an explicit object")
    for key in ("core_quest", "driving_force", "volume1_hook", "endgame_condition"):
        if not _text(plotline.get(key)):
            _v3_error("main_plotline", f"missing required field: {key}")
    arc = plotline.get("progression_arc")
    if not isinstance(arc, list) or not 2 <= len(arc) <= 5:
        _v3_error("main_plotline.progression_arc", "must contain 2-5 causal stages")
    for index, item in enumerate(arc):
        if not _text(item.get("stage")) or not _text(item.get("goal")):
            _v3_error(f"main_plotline.progression_arc[{index}]", "stage and goal are required")

    long_arc = _get_world_mystery(manifest)
    if long_arc.get("mode") == "present":
        ladder = long_arc.get("decryption_ladder")
        if not isinstance(ladder, list) or not ladder:
            _v3_error("long_arc_question.decryption_ladder", "must contain at least one reveal stage")
        for index, item in enumerate(ladder):
            if not _text(item.get("stage")) or not _text(item.get("truth")):
                _v3_error(f"long_arc_question.decryption_ladder[{index}]", "stage and truth are required")

    step3 = _object(manifest.get("step3_world"))
    _validate_text_list("step3_world.iron_rules", step3.get("iron_rules"), minimum=1)
    opposition = _object(step3.get("opposition"))
    for key in ("name", "kind", "interest", "conflict", "first_pressure"):
        if not _text(opposition.get(key)):
            _v3_error("step3_world.opposition", f"missing required field: {key}")

    step4 = _object(manifest.get("step4_outline"))
    if not _text(step4.get("structure_mode")):
        _v3_error("step4_outline.structure_mode", "is required")
    acts = step4.get("acts")
    if not isinstance(acts, list) or not acts:
        _v3_error("step4_outline.acts", "must contain at least one structural segment")
    for index, act in enumerate(acts):
        field = f"step4_outline.acts[{index}]"
        if not isinstance(act, dict):
            _v3_error(field, "must be an object")
        for key in ("name", "volumes", "arc", "stakes"):
            if not _text(act.get(key)):
                _v3_error(field, f"missing required field: {key}")

    story_errors = story_map_errors(step4, required=True)
    if story_errors:
        _v3_error("step4_outline.story_map", story_errors[0]["message"])
    _normalized_long_term_commitments(step4)

    volume1 = _object(manifest.get("step5_volume1"))
    for key in ("title", "spine", "climax", "next_volume_hook"):
        if not _text(volume1.get(key)):
            _v3_error("step5_volume1", f"missing required field: {key}")
    for key in ("word_budget", "chapters_budget"):
        value = volume1.get(key)
        if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
            _v3_error(f"step5_volume1.{key}", "must be a positive integer")
    if volume1["chapters_budget"] < 3:
        _v3_error("step5_volume1.chapters_budget", "must cover the three seed chapters")
    if volume1["word_budget"] > book_words:
        _v3_error("step5_volume1.word_budget", "cannot exceed book_words")
    chapter_target = _hatch_chapter_target()
    expected_volume_chapters = expected_total_chapters(volume1["word_budget"], chapter_target)
    if volume1["chapters_budget"] != expected_volume_chapters:
        _v3_error(
            "step5_volume1.chapters_budget",
            f"must equal ceil(word_budget / {chapter_target}) = {expected_volume_chapters}",
        )
    _all_volume_outline_parts(manifest)

    constraints_mode = _text(manifest.get("hard_constraints_mode")).lower()
    constraints = manifest.get("hard_constraints", [])
    if constraints_mode not in {"present", "none"}:
        raise LedgerError(
            "hatch_unresolved",
            "hard_constraints_mode must be explicitly present or none",
            {"field": "hard_constraints_mode"},
        )
    if constraints_mode == "present":
        _validate_text_list("hard_constraints", constraints, minimum=1)
    elif constraints not in (None, []):
        _v3_error("hard_constraints", "must be empty when hard_constraints_mode is none")

    # 视角结构与平台尺度（可选；声明即必须形状合法——半非法字段比缺字段更危险）
    pov = manifest.get("narrative_pov")
    if pov is not None:
        if not isinstance(pov, dict):
            _v3_error("narrative_pov", "must be an object")
        structure = _text(pov.get("structure"))
        if structure not in POV_STRUCTURES:
            _v3_error(
                "narrative_pov.structure",
                f"must be one of {list(POV_STRUCTURES)}",
            )
        if "anchor" in pov and not isinstance(pov["anchor"], str):
            _v3_error("narrative_pov.anchor", "must be a string")
        if structure != "single_limited" and _text(pov.get("switch_granularity")) not in POV_GRANULARITIES:
            _v3_error(
                "narrative_pov.switch_granularity",
                "must be chapter or volume when structure switches viewpoints",
            )
    fence = manifest.get("content_fence")
    if fence is not None:
        if not isinstance(fence, dict):
            _v3_error("content_fence", "must be an object")
        tier = _text(fence.get("tier"))
        if tier not in FENCE_TIERS:
            _v3_error("content_fence.tier", f"must be one of {list(FENCE_TIERS)}")
        if "notes" in fence and not isinstance(fence["notes"], str):
            _v3_error("content_fence.notes", "must be a string")

    # glossary 源头校验（glossary 若被填成「词条→释义」，正典核心词会被自己的
    # 门禁摁掉）。
    # glossary 只接受「禁用旧写法 → 规范写法」；值像释义句、或禁用串撞上
    # 主线/卷脊要求的词，都在开书时拒绝——坏配置不该有出生的机会。
    glossary_manifest = manifest.get("glossary")
    if glossary_manifest is not None:
        if not isinstance(glossary_manifest, dict):
            _v3_error("glossary", "must be an object of {禁用旧写法: 规范写法}")
        from ..content.gates import value_looks_like_definition

        required_text = "；".join(
            _text(source.get(key))
            for source, keys in (
                (plotline, ("core_quest", "volume1_hook", "endgame_condition")),
                (volume1, ("spine", "climax")),
            )
            for key in keys
        )
        for banned, canonical in glossary_manifest.items():
            banned_text, canonical_text = _text(banned), _text(canonical)
            if not banned_text or not canonical_text or banned_text == canonical_text:
                _v3_error("glossary", f"entry '{banned}': key and value must be distinct non-empty strings")
            if value_looks_like_definition(canonical_text):
                _v3_error(
                    "glossary",
                    f"entry '{banned}': value looks like a definition, not a canonical spelling; "
                    "glossary is {禁用旧写法: 规范写法}, never {词条: 释义}",
                )
            if banned_text in required_text:
                _v3_error(
                    "glossary",
                    f"entry '{banned}': this term is required by the mainline/volume spine — "
                    "banning it contradicts the book itself",
                )

    chapters = _object(manifest.get("step6_beats")).get("chapters")
    if not isinstance(chapters, list) or len(chapters) != 3:
        _v3_error("step6_beats.chapters", "must contain exactly chapters 1, 2, and 3")
    numbers = [chapter.get("chapter") if isinstance(chapter, dict) else None for chapter in chapters]
    if numbers != [1, 2, 3]:
        _v3_error("step6_beats.chapters", "chapter numbers must be [1, 2, 3] in order")
    for chapter_index, chapter in enumerate(chapters):
        field = f"step6_beats.chapters[{chapter_index}]"
        try:
            validate_knowledge_refs(chapter.get("knowledge_refs"), chapter=chapter_index + 1)
        except LedgerError as exc:
            _v3_error(f"{field}.knowledge_refs", exc.message)
        if not _text(chapter.get("title")):
            _v3_error(f"{field}.title", "is required")
        beats = chapter.get("beats")
        # 五场是默认节奏；特殊短章可以少排，但不得提交空章或丢掉每场的因果锚点。
        if not isinstance(beats, list) or not beats:
            _v3_error(f"{field}.beats", "must contain at least one scene beat")
        beat_ids: list[str] = []
        for beat_index, beat in enumerate(beats):
            beat_field = f"{field}.beats[{beat_index}]"
            if not isinstance(beat, dict):
                _v3_error(beat_field, "must be an object")
            beat_id = _text(beat.get("id"))
            text = _text(beat.get("text"))
            must = _text(beat.get("must"))
            if not beat_id or not text or not must:
                _v3_error(beat_field, "id, text, and must are required")
            if must not in text:
                _v3_error(f"{beat_field}.must", "must be a concrete substring of beat text")
            beat_ids.append(beat_id)
        if len(set(beat_ids)) != len(beat_ids):
            _v3_error(f"{field}.beats", "beat ids must be unique inside the chapter")

    opening_phase = _initial_phase(step4, volume1, len(chapters))
    normalized_seed_refs = [
        {
            **chapter,
            "phase_id": chapter.get("phase_id") or "phase-opening",
            "story_stage": chapter.get("story_stage") or step4["acts"][0]["name"],
            "thread_refs": chapter.get("thread_refs") or _opening_chapter_refs(step4, index, opening_phase)[0],
            "clock_refs": chapter.get("clock_refs") or _opening_chapter_refs(step4, index, opening_phase)[1],
        }
        for index, chapter in enumerate(chapters)
    ]
    seed_story_errors = story_map_errors(
        step4,
        chapters=normalized_seed_refs,
        phases=[opening_phase],
        required=True,
    )
    if seed_story_errors:
        _v3_error("step6_beats.story_map_refs", seed_story_errors[0]["message"])


def validate_hatch_manifest(manifest: dict[str, Any]) -> dict[str, Any]:
    """Validate that the choice-driven hatch manifest has the required keys."""
    if not isinstance(manifest, dict):
        raise LedgerError("invalid_manifest", "hatch manifest must be a JSON object")

    schema_version = _schema_version(manifest)
    if schema_version != 3:
        raise LedgerError(
            "invalid_hatch_schema",
            "book hatching only accepts novel-ledger.hatch.v3",
        )

    for key in ("step1_hook", "step2_protagonist", "step3_world", "step4_outline", "step5_volume1", "step6_beats"):
        if not isinstance(manifest.get(key), dict):
            _v3_error(key, "must be an object")

    book_words = manifest.get("book_words")
    if book_words is not None and (
        isinstance(book_words, bool) or not isinstance(book_words, int) or book_words <= 0
    ):
        raise LedgerError("invalid_book_words", "book_words must be a positive integer")

    protagonist = _get_protagonist(manifest)
    if not protagonist:
        raise LedgerError(
            "missing_protagonist",
            "hatch manifest must provide protagonist at top level or step2_protagonist.name",
        )

    # 验证 beats
    step6 = manifest.get("step6_beats")
    chapters = None
    if isinstance(step6, dict) and isinstance(step6.get("chapters"), list):
        chapters = step6["chapters"]
    elif isinstance(manifest.get("chapters"), list):
        chapters = manifest["chapters"]

    if not chapters:
        raise LedgerError(
            "missing_beats",
            "hatch manifest must provide chapters with beats (in step6_beats.chapters or top-level chapters)",
        )

    for ch in chapters:
        if not isinstance(ch, dict):
            raise LedgerError(
                "invalid_beats",
                "each chapter in the hatch manifest must be an object",
            )
        if not isinstance(ch.get("beats"), list) or len(ch["beats"]) == 0:
            raise LedgerError(
                "invalid_beats",
                f"chapter {ch.get('chapter', '?')} must contain a non-empty beats list",
            )

    # Every v3 manifest must seed one executable, unambiguous plan.
    chapter_numbers = [ch.get("chapter") for ch in chapters]
    if any(isinstance(number, bool) or not isinstance(number, int) or number <= 0 for number in chapter_numbers):
        raise LedgerError("invalid_beats", "chapter numbers must be positive integers")
    if chapter_numbers != list(range(1, len(chapter_numbers) + 1)):
        raise LedgerError(
            "invalid_beats",
            "seed chapter numbers must start at 1, be unique, contiguous, and ordered",
            {"planned": chapter_numbers},
        )

    _validate_v3_contract(manifest)
    _narrative_contract_from_manifest(manifest)

    return manifest


def render_intent_markdown(manifest: dict[str, Any]) -> str:
    """Render comprehensive intent.md containing all essential novel hatching elements."""
    title = manifest.get("title") or "未定名"
    protagonist = _get_protagonist(manifest)
    step1 = _object(manifest.get("step1_hook"))
    step2 = _object(manifest.get("step2_protagonist"))
    step3 = _object(manifest.get("step3_world"))
    step5 = _object(manifest.get("step5_volume1"))
    hard_constraints = manifest.get("hard_constraints") or []
    plotline = _get_main_plotline(manifest)
    mechanism = _get_cheat_constraint(manifest)
    material_life = _get_sustenance_craft(manifest)
    long_arc = _get_world_mystery(manifest)
    relationship_structure = _object(manifest.get("relationship_structure"))

    genre_tags = step1.get("genre_tags") or []
    if isinstance(genre_tags, list):
        genre_str = " / ".join(str(t) for t in genre_tags) or "未设定"
    else:
        genre_str = str(genre_tags)

    concept = step1.get("concept") or step1.get("one_sentence_pitch") or "未设定"
    audience = step1.get("target_audience") or "未设定"
    selling_points = step1.get("selling_points") or "未设定"

    initial_status = step2.get("initial_status") or "未设定"
    desire_surface = step2.get("desire_surface") or "未设定"
    desire_deep = step2.get("desire_deep") or "未设定"
    fatal_wound = step2.get("fatal_wound") or step2.get("core_pressure") or "未设定"
    persona = step2.get("persona") or "未设定"
    flaw = step2.get("flaw") or step2.get("limitation") or "未设定"
    skillset = step2.get("skillset") or "未设定"

    protagonist_archetype = (
        step1.get("protagonist_archetype")
        or step2.get("protagonist_archetype")
        or "未设定"
    )
    progression_type = step1.get("plot_architecture") or step1.get("progression_type") or "未设定"
    narrative_tone = step1.get("narrative_tone") or "未设定"

    lines = [
        f"# 《作者意图书与红线》（{title}）",
        "",
        "> 本文件由选择式开书流程（Choice-Driven Hatching）自动组装签发，是全书最高意志真源。",
    ]
    section_no = 0

    def start_section(section_title: str) -> None:
        nonlocal section_no
        section_no += 1
        lines.extend(["", "---", "", _section_heading(section_no, section_title), ""])

    start_section("基本信息与商业定位")
    positioning_lines = [
        "",
        f"- **书名**：{title}",
        f"- **题材标签**：{genre_str}",
        f"- **主角姓名**：{protagonist}",
        f"- **主角性格流派**：{protagonist_archetype}",
        f"- **叙事结构模式**：{progression_type}",
        f"- **叙事基调**：{narrative_tone}",
        f"- **核心高概念（One-Sentence Pitch）**：{concept}",
        f"- **核心卖点与爽点类型**：{selling_points}",
        f"- **目标受众与期望体感**：{audience}",
    ]
    lines.extend(positioning_lines)
    # 视角结构与平台尺度（随门 8 声明；未声明不渲染这两行）
    pov_sentence = render_narrative_pov(manifest.get("narrative_pov"))
    if pov_sentence:
        lines.append(f"- **视角结构**：{pov_sentence}")
    fence_sentence = render_content_fence(manifest.get("content_fence"))
    if fence_sentence:
        lines.append(f"- **平台尺度**：{fence_sentence}；具体禁项由下方红线承接")

    start_section("主角动力引擎（人设动力学与致命伤口）")
    lines.extend([
        "",
        f"- **初始处境与阶层**：{initial_status}",
        "1. **核心动机（Desire）**：",
        f"   - 近期目标（表层欲望）：{desire_surface}",
        f"   - 终极追求（深层欲望）：{desire_deep}",
        "2. **核心压力 / 不可逆伤口**：",
        f"   - {fatal_wound}",
        "3. **性格底色与行事准则**：",
        f"   - {persona}",
        "4. **核心缺陷与负面特质（Flaw）**：",
        f"   - {flaw}",
        "5. **核心技能与依凭抓手（Skillset）**：",
        f"   - {skillset}",
    ])

    if material_life.get("mode") == "present":
        lines.extend(["6. **物质生活与社会身份（Material Life）**："])
        for label, key in (
            ("谋生方式", "profession"),
            ("资源循环", "income_loop"),
            ("社会接点", "social_network"),
            ("公开身份", "cover_persona"),
        ):
            if _text(material_life.get(key)):
                lines.append(f"   - {label}：{material_life[key]}")
    else:
        lines.append("6. **物质生活与社会身份**：none（不单列职业/资源循环）")

    if plotline.get("mode") == "present":
        start_section("全书核心主线与终极使命（Central Plotline & Grand Quest）")
        lines.extend([
            "> 主线是全书行动与因果的贯穿轴，各卷应明确承接关系。",
            "",
        ])
        for label, key in (
            ("核心主线使命（Core Quest）", "core_quest"),
            ("主线驱动源泉（Driving Force）", "driving_force"),
            ("首卷与全书主线咬合（Volume 1 Hook）", "volume1_hook"),
            ("主线终局胜利标志（Endgame Victory）", "endgame_condition"),
        ):
            if _text(plotline.get(key)):
                lines.append(f"- **{label}**：{plotline[key]}")
        if plotline.get("progression_arc"):
            lines.extend([
                "",
                "### 主线阶段因果递进链（Progression Arc）",
                "",
                "| 阶段 | 核心推进目标与因果转折 |",
                "|---|---|",
            ])
            for arc in plotline["progression_arc"]:
                lines.append(f"| {arc['stage']} | {arc['goal']} |")

    if long_arc.get("mode") == "present":
        start_section("长线问题与揭示阶梯（Long-Arc Question）")
        for label, key in (
            ("核心长线问题", "core_mystery"),
            ("表层认知", "surface_illusion"),
        ):
            if _text(long_arc.get(key)):
                lines.append(f"- **{label}**：{long_arc[key]}")
        if long_arc.get("decryption_ladder"):
            lines.extend([
                "",
                "### 分阶段揭示阶梯",
                "",
                "| 阶段 | 核心线索与认知变化 |",
                "|---|---|",
            ])
            for item in long_arc["decryption_ladder"]:
                lines.append(f"| {item['stage']} | {item['truth']} |")
    else:
        start_section("长线问题（Long-Arc Question）")
        lines.append("- **长线问题决策**：none（不设置独立谜题/揭示阶梯）")

    start_section("核心关系结构（Core Relationships）")
    if relationship_structure.get("mode") == "none":
        lines.append("- **关系结构决策**：none（不设置固定核心关系线）")
    else:
        lines.append(f"- **关系结构模式**：{relationship_structure.get('pattern')}")
        for item in relationship_structure.get("relationships") or []:
            participants = " / ".join(str(name) for name in item.get("participants") or [])
            lines.extend([
                "",
                f"### {item.get('name')}",
                f"- **参与者**：{participants}",
                f"- **关系类型**：{item.get('relationship_type')}",
                f"- **独立诉求**：{item.get('independent_goal')}",
                f"- **边界**：{item.get('boundary')}",
                f"- **变化节奏**：{item.get('change_arc')}",
            ])

    if mechanism.get("mode") == "present":
        start_section("故事机制、代价与边界（Story Mechanism & Constraints）")
        for label, key in (
            ("机制名称", "name"),
            ("运作原理与能力边界", "mechanism"),
            ("代价与反噬", "cost_and_backlash"),
            ("硬性限制与触发盲区", "limitations"),
            ("应对与规避", "workaround"),
        ):
            if _text(mechanism.get(key)):
                lines.append(f"- **{label}**：{mechanism[key]}")
    else:
        start_section("故事机制、代价与边界（Story Mechanism & Constraints）")
        lines.append("- **故事机制决策**：none（不设置额外能力或装置型机制）")

    start_section("世界硬规则与能力边界（正典承重墙）")
    lines.extend([
        "### 1. 力量与资源三大守恒铁律",
    ])

    iron_rules = step3.get("iron_rules") or []
    if iron_rules and isinstance(iron_rules, list):
        for idx, rule in enumerate(iron_rules, 1):
            lines.append(f"{idx}. {rule}")
    else:
        lines.append("1. 未声明；不得由系统代填项目事实。")

    power_sys = step3.get("power_system")
    if power_sys:
        lines.extend([
            "",
            "### 2. 能力与资源限制体系",
            f"- {power_sys}",
        ])

    economy = step3.get("economy")
    if economy:
        lines.extend([
            "",
            "### 3. 稀缺资源与分配秩序",
            f"- {economy}",
        ])

    start_section("核心对抗与人物生态网络")

    opposition = step3.get("opposition")
    if isinstance(opposition, dict) and opposition:
        lines.extend([
            "### 1. 核心对抗来源",
            f"- **名称**：{opposition['name']}",
            f"- **类型**：{opposition['kind']}",
            f"- **合理诉求 / 运转逻辑**：{opposition['interest']}",
            f"- **与主角的核心冲突**：{opposition['conflict']}",
            f"- **首卷直接压力**：{opposition['first_pressure']}",
        ])
    first_foe = step5.get("first_foe") or step3.get("first_foe")
    if first_foe:
        lines.extend([
            "",
            "### 2. 首卷直接施压者",
            f"- {first_foe}",
        ])

    allies = step3.get("allies")
    if allies:
        lines.extend([
            "",
            "### 3. 关键盟友与互信边界",
            f"- {allies}",
        ])

    start_section("量化口径真源表（跨章对账基准）")
    lines.extend([
        "| 口径项 | 定值基准 | 对账核算说明 | 禁用写法 |",
        "|---|---|---|---|",
    ])

    quant_items = manifest.get("quant_items") or manifest.get("quant_keys") or []
    if quant_items and isinstance(quant_items, list):
        for q in quant_items:
            if isinstance(q, dict):
                lines.append(
                    f"| {q.get('key', '-')} | {q.get('value', '-')} | {q.get('rule', '-')} | {q.get('banned', '-')} |"
                )
            else:
                lines.append(f"| {q} | 基准定值 | 全书单一取值统一对账 | 旧写法 |")
    else:
        lines.append("| 未声明 | - | 不得由系统代填项目数值 | - |")

    start_section("作者绝对红线（Hard Constraints）")

    if hard_constraints and isinstance(hard_constraints, list):
        for idx, constraint in enumerate(hard_constraints, 1):
            lines.append(f"{idx}. **{constraint}**")
    else:
        lines.append("- 未声明；不得由系统替作者创建红线。")

    lines.append("")
    return "\n".join(lines)


def render_outline_markdown(manifest: dict[str, Any]) -> str:
    """Render outline.md based on step4 (acts, milestones) and step5 (volume1)."""
    title = manifest.get("title") or "未定名"
    book_words = manifest.get("book_words") or 2000000
    step4 = _object(manifest.get("step4_outline"))
    step5 = _object(manifest.get("step5_volume1"))
    event_spine = _object(step4.get("event_spine"))
    plotline = _get_main_plotline(manifest)
    long_arc = _get_world_mystery(manifest)

    acts = step4.get("acts") or []
    milestones = step4.get("milestones") or []
    commitments = _normalized_long_term_commitments(step4)
    chapter_words_target = _hatch_chapter_target()
    total_chapters = expected_total_chapters(book_words, chapter_words_target)

    lines = [
        f"# 《全书大纲》（{title}）",
        "",
        "> 本文件由选择式开书流程（Choice-Driven Hatching）自动生成，记录书级连贯性设计理由与幕卷规划。",
        "",
        "---",
        "",
        "## 〇、目标规模",
        "",
        f"- **全书目标字数**：{book_words}",
        f"- **目标单章字数**：{chapter_words_target}",
        f"- **预计总章数**：{total_chapters}",
    ]
    section_no = 0

    def start_section(section_title: str) -> None:
        nonlocal section_no
        section_no += 1
        lines.extend(["", "---", "", _section_heading(section_no, section_title), ""])

    if plotline.get("mode") == "present":
        start_section("全书核心主线与阶段阶梯（Central Plotline & Progression Arc）")
        for label, key in (
            ("核心主线使命（Core Quest）", "core_quest"),
            ("主线驱动力（Driving Force）", "driving_force"),
            ("首卷主线咬合点（Volume 1 Hook）", "volume1_hook"),
            ("终局达成标志（Endgame Victory）", "endgame_condition"),
        ):
            if _text(plotline.get(key)):
                lines.append(f"- **{label}**：{plotline[key]}")
        if plotline.get("progression_arc"):
            lines.extend([
                "",
                "### 主线阶段阶梯与因果递进",
                "",
                "| 阶段 | 推进目标与因果转折 |",
                "|---|---|",
            ])
            for arc in plotline["progression_arc"]:
                lines.append(f"| {arc['stage']} | {arc['goal']} |")

    if long_arc.get("mode") == "present":
        start_section("长线问题与分阶段揭示（Long-Arc Question）")
        for label, key in (
            ("核心长线问题", "core_mystery"),
            ("表层认知", "surface_illusion"),
        ):
            if _text(long_arc.get(key)):
                lines.append(f"- **{label}**：{long_arc[key]}")
        if long_arc.get("decryption_ladder"):
            lines.extend([
                "",
                "### 分阶段揭示节奏表",
                "",
                "| 阶段 | 核心线索与认知变化 |",
                "|---|---|",
            ])
            for item in long_arc["decryption_ladder"]:
                lines.append(f"| {item['stage']} | {item['truth']} |")

    start_section("幕结构")
    lines.extend([
        "| 幕 | 卷区间 | 弧（入口态→出口态） | 升级（stakes / 力量 / 资源） |",
        "|---|---|---|---|",
    ])

    if acts and isinstance(acts, list):
        for a in acts:
            if not isinstance(a, dict):
                continue
            lines.append(
                f"| {a.get('name', '第N幕')} | {a.get('volumes', '-')} | {a.get('arc', '-')} | {a.get('stakes', '-')} |"
            )
    else:
        lines.append("| 未声明 | - | 不得由系统代填故事结构 | - |")

    start_section("全书分卷总纲（开书前一次签齐，逐卷细化）")
    volume_outlines, volume_contract = _all_volume_outline_parts(manifest)
    lines.append(f"- **签约卷数**：{volume_contract['volume_count']}；所有卷字数预算合计 {volume_contract['book_words']}。")
    for ident, volume in volume_outlines.items():
        lines.extend(["", f"### 第{volume['volume']}卷：{volume['title']}（{ident}）", "",
                      f"- **字数／章数预算**：{volume['word_budget']}／{volume['chapters_budget']}"])
        for label, field in (("卷脊与目标", "spine"), ("本卷目标", "goal"), ("剧情职责", "plot_role"),
                             ("承接前卷／开篇依据", "inherits"), ("矛盾推进与人物线", "advances"),
                             ("通向全书终局", "ending_direction"), ("下一卷接口／收束去向", "next_handoff")):
            lines.append(f"- **{label}**：{volume[field]}")
        lines.extend(["", f"#### 本卷完整卷纲（{outline_han_count(volume['outline'])} 个汉字）", "", volume["outline"]])

    start_section("主线与支线事件链（幕级骨架）")
    lines.extend([
        "> 这里只固定有限的阶段触点；具体章拍随写作窗口滚动生成，避免提前穷举全书章节。",
        "",
        "| ID | 类型 | 线路 | 作用 | 与主线的因果咬合 | 开启幕 → 回收幕 | 幕级触点 |",
        "|---|---|---|---|---|---|---|",
    ])
    render_threads: list[dict[str, Any]] = []
    if isinstance(event_spine.get("mainline"), dict):
        render_threads.append({**event_spine["mainline"], "kind": "main"})
    render_threads.extend(
        {**item, "kind": "subplot"}
        for item in (event_spine.get("subplots") or [])
        if isinstance(item, dict)
    )
    for thread in render_threads:
        if not isinstance(thread, dict):
            continue
        touchpoints = "<br>".join(
            f"{point.get('stage', '-')}：{point.get('event', '-')} → {point.get('change', '-')}"
            for point in (thread.get("events") or [])
            if isinstance(point, dict)
        ) or "-"
        lines.append(
            f"| {thread.get('id', '-')} | {thread.get('kind', '-')} | {thread.get('name', '-')} | "
            f"{thread.get('purpose', '-')} | {thread.get('mainline_link', '-')} | "
            f"{thread.get('open_stage', '-')} → {thread.get('payoff_stage', '-')} | {touchpoints} |"
        )

    start_section("主角／对手／世界三线时钟")
    for clock in event_spine.get("timelines") or []:
        if not isinstance(clock, dict):
            continue
        lines.extend([
            f"### {clock.get('name', '-')}（{clock.get('kind', '-')} / {clock.get('id', '-')}）",
            "",
            f"- **起始状态**：{clock.get('start_state', '-')}",
        ])
        for event in clock.get("events") or []:
            if isinstance(event, dict):
                lines.append(
                    f"- **{event.get('order', '-')}. {event.get('stage', '-')}**：{event.get('event', '-')}；"
                    f"截止条件：{event.get('deadline', '-')}；错失后果：{event.get('consequence', '-')}"
                )
        lines.append("")

    start_section("幕级情节起伏曲线")
    lines.extend([
        "| 幕 | 强度（1-5） | 节奏模式 | 核心压力 | 关键转折 | 阶段兑现 | 下一失衡 |",
        "|---|---:|---|---|---|---|---|",
    ])
    for point in event_spine.get("tension_curve") or []:
        if isinstance(point, dict):
            lines.append(
                f"| {point.get('stage', '-')} | {point.get('level', '-')} | {point.get('mode', '-')} | "
                f"{point.get('pressure', '-')} | {point.get('turn', '-')} | {point.get('payoff', '-')} | "
                f"{point.get('next_imbalance', '-')} |"
            )

    start_section("第一卷蓝图（首卷设计）")
    lines.extend([
        f"- **卷名**：{step5.get('title', '未设定')}",
        f"- **字数预算**：{step5.get('word_budget', '未设定')}",
        f"- **章数预算**：{step5.get('chapters_budget', '未设定')}",
        f"- **卷脊核心目标**：{step5.get('spine', '未设定')}",
        f"- **卷终大兑现（Climax）**：{step5.get('climax', '未设定')}",
    ])
    if _text(step5.get("next_volume_hook")):
        lines.append(f"- **下一卷接口**：{step5['next_volume_hook']}")

    start_section("长线承诺账（大伏笔埋收规划）")
    lines.extend([
        "| ID | 承诺 | 埋设卷 | 计划回收卷 | 说明 |",
        "|---|---|---|---|---|",
    ])

    if commitments:
        for c in commitments:
            lines.append(
                f"| {c['id']} | {c['promise']} | {c['planted_volume']} | {c['resolved_volume']} | {c['description'] or '-'} |"
            )
    else:
        lines.append("| - | 未声明 | - | - | 不得由系统代填长线承诺 |")

    start_section("主角弧里程碑")
    lines.extend([
        "| 里程碑 | 预估章节 | 类型 | 说明 |",
        "|---|---|---|---|",
    ])

    if milestones and isinstance(milestones, list):
        for m in milestones:
            if not isinstance(m, dict):
                continue
            lines.append(
                f"| {m.get('milestone', m.get('description', '-'))} | {m.get('chapter', 1)} | {m.get('kind', 'volume_payoff')} | {m.get('description', '-')} |"
            )
    else:
        lines.append("| 未声明 | - | - | 不得由系统代填角色弧 |")

    lines.append("")
    return "\n".join(lines)


def render_canon_markdowns(manifest: dict[str, Any]) -> dict[str, str]:
    """Render comprehensive canon markdown files for book/kb/canon/."""
    title = manifest.get("title") or "未定名"
    step2 = _object(manifest.get("step2_protagonist"))
    step3 = _object(manifest.get("step3_world"))
    protagonist = _get_protagonist(manifest)

    # 1. world_rules.md
    iron_rules = step3.get("iron_rules") or []
    power_sys = _text(step3.get("power_system"))
    mechanism = _get_cheat_constraint(manifest)
    material_life = _get_sustenance_craft(manifest)

    rules_title = "世界底层运转规则与能力边界"
    rules_content = [
        f"# 《{title}》{rules_title}",
        "",
    ]
    if iron_rules and isinstance(iron_rules, list):
        rules_content.extend(["## 规则与守恒铁律【硬】", ""])
        for idx, rule in enumerate(iron_rules, 1):
            rules_content.append(f"{idx}. {rule}")

    if mechanism.get("mode") == "present":
        name = _text(mechanism.get("name")) or "故事机制"
        rules_content.extend(["", f"## 故事机制与边界：{name}【硬】"])
        for label, key in (
            ("机制名称", "name"),
            ("运作原理与能力边界", "mechanism"),
            ("代价与反噬", "cost_and_backlash"),
            ("硬性限制", "limitations"),
            ("应对途径", "workaround"),
        ):
            if _text(mechanism.get(key)):
                rules_content.append(f"- {label}：{mechanism[key]}")

    if power_sys:
        rules_content.extend([
            "",
            "## 能力与限制体系【硬】",
            f"- 体系说明：{power_sys}",
        ])

    # 长线谜题的“表层认知”是角色此时相信的解释，不是世界客观规则。
    # 它与揭示阶梯只留在编辑大纲 / plan.book_outline，不能进入硬正典。
    rules_content.append("")

    # 2. characters.md
    opposition = step3.get("opposition") or {}
    allies = _text(step3.get("allies"))
    chars_content = [
        f"# 《{title}》角色名录",
        "",
        f"## 主角：{protagonist}【硬】",
        f"- 姓名：{protagonist}",
    ]
    protagonist_fields = (
        ("初始处境", "initial_status"),
        ("表层目标", "desire_surface"),
        ("深层欲望", "desire_deep"),
        ("核心压力 / 不可逆伤口", "fatal_wound" if _text(step2.get("fatal_wound")) else "core_pressure"),
        ("性格底色", "persona"),
        ("核心缺陷 / 限制", "flaw" if _text(step2.get("flaw")) else "limitation"),
        ("专长抓手", "skillset"),
    )
    for label, key in protagonist_fields:
        if _text(step2.get(key)):
            chars_content.append(f"- {label}：{step2[key]}")
    if material_life.get("mode") == "present":
        for label, key in (
            ("谋生方式", "profession"),
            ("资源循环", "income_loop"),
            ("社会接点", "social_network"),
            ("公开身份", "cover_persona"),
        ):
            if _text(material_life.get(key)):
                chars_content.append(f"- {label}：{material_life[key]}")
    chars_content.append("")

    relationship_structure = _object(manifest.get("relationship_structure"))
    if _text(relationship_structure.get("mode")).lower() == "none":
        chars_content.extend(["## 核心关系结构【硬】", "- 决策：none（不设置固定核心关系线）", ""])
    else:
        chars_content.extend([
            "## 核心关系结构【硬】",
            f"- 结构模式：{relationship_structure.get('pattern')}",
        ])
        for item in relationship_structure.get("relationships") or []:
            participants = " / ".join(str(name) for name in item.get("participants") or [])
            chars_content.extend([
                f"### {item.get('name')}",
                f"- 参与者：{participants}",
                f"- 关系类型：{item.get('relationship_type')}",
                f"- 独立诉求：{item.get('independent_goal')}",
                f"- 边界：{item.get('boundary')}",
                f"- 变化节奏：{item.get('change_arc')}",
                "",
            ])

    if isinstance(opposition, dict) and opposition:
        chars_content.extend([
            f"## 核心对抗：{opposition.get('name')}【硬】",
            f"- 类型：{opposition.get('kind')}",
            f"- 合理诉求 / 运转逻辑：{opposition.get('interest')}",
            f"- 核心冲突：{opposition.get('conflict')}",
            f"- 首卷压力：{opposition.get('first_pressure')}",
            "",
        ])

    if allies:
        chars_content.extend(["## 关键盟友【硬】", f"- 盟友与互信生态：{allies}", ""])

    # 3. economy.md
    economy = _text(step3.get("economy"))
    economy_content = [
        f"# 《{title}》经济与资源体系",
        "",
    ]
    if economy:
        economy_content.extend(["## 货币与资源分配【硬】", f"- 资源流向：{economy}", ""])

    return {
        "world_rules.md": "\n".join(rules_content),
        "characters.md": "\n".join(chars_content),
        "economy.md": "\n".join(economy_content),
    }


def _narrative_contract_from_manifest(manifest: dict[str, Any]) -> dict[str, Any]:
    """Retain the approved narrative wording; no summaries or new obligations."""
    def fields(source: Any, names: tuple[str, ...]) -> dict[str, Any]:
        source = _object(source)
        return {name: copy.deepcopy(source[name]) for name in names if name in source}

    contract = {
        "schema": NARRATIVE_CONTRACT_SCHEMA,
        "source_schema": manifest.get("schema"),
        "reader_promise": fields(manifest.get("step1_hook"), (
            "concept", "genre_tags", "target_audience", "selling_points", "narrative_tone", "plot_architecture",
        )),
        "protagonist_engine": fields(manifest.get("step2_protagonist"), (
            "name", "initial_status", "desire_surface", "desire_deep", "fatal_wound", "core_pressure",
            "persona", "flaw", "limitation", "skillset",
        )),
        "main_arc": fields(manifest.get("main_plotline"), (
            "mode", "core_quest", "driving_force", "volume1_hook", "endgame_condition", "progression_arc",
        )),
        "hard_constraints_mode": manifest.get("hard_constraints_mode"),
        "hard_constraints": copy.deepcopy(manifest.get("hard_constraints") or []),
        "world_rules": fields(manifest.get("step3_world"), (
            "iron_rules", "power_system", "economy", "opposition", "allies",
        )),
    }
    for name in ("story_mechanism", "material_life", "narrative_pov", "content_fence"):
        if name in manifest:
            contract["world_rules"][name] = copy.deepcopy(manifest[name])
    if "relationship_structure" in manifest:
        contract["core_relationships"] = copy.deepcopy(manifest["relationship_structure"])
    # Theme is an optional author declaration, not a mandatory invented thesis.
    for name in ("theme", "themes", "thematic_question"):
        if name in manifest:
            contract[name] = copy.deepcopy(manifest[name])
        elif name in _object(manifest.get("step4_outline")):
            contract[name] = copy.deepcopy(manifest["step4_outline"][name])
    return validate_narrative_contract(contract)


def _all_volume_outline_parts(manifest: dict[str, Any]) -> tuple[dict[str, Any], dict[str, Any]]:
    """Require real authored outlines for the complete book before any file write."""
    raw = manifest.get("volume_outline_contract")
    if not isinstance(raw, dict) or raw.get("schema") != VOLUME_OUTLINE_SCHEMA:
        _v3_error("volume_outline_contract", f"must sign {VOLUME_OUTLINE_SCHEMA} with every volume before hatching")
    count, entries = raw.get("volume_count"), raw.get("volumes")
    if isinstance(count, bool) or not isinstance(count, int) or count <= 0 or not isinstance(entries, list) or len(entries) != count:
        _v3_error("volume_outline_contract", "volume_count must equal the complete ordered volume list length")
    volumes = {}
    for number, entry in enumerate(entries, 1):
        if not isinstance(entry, dict) or entry.get("volume") != number or isinstance(entry.get("volume"), bool):
            _v3_error(f"volume_outline_contract.volumes[{number - 1}]", "volumes must be unique and ordered from 1 through volume_count")
        for field in ("word_budget", "chapters_budget"):
            value = entry.get(field)
            if isinstance(value, bool) or not isinstance(value, int) or value <= 0:
                _v3_error(f"volume_outline_contract.volumes[{number - 1}].{field}", "must be a positive integer")
        volumes[f"vol-{number:04d}"] = copy.deepcopy(entry)
    pace = _hatch_chapter_target()
    signed = sign_volume_outline_contract(volumes, manifest["book_words"], pace)
    candidate = {"volume_outline_contract": signed, "volumes": volumes, "chapters": [],
                 "book_outline": {**_object(manifest.get("step4_outline")), "book_words": manifest["book_words"], "volume_outline_schema": VOLUME_OUTLINE_SCHEMA}}
    errors = volume_outline_errors(candidate, required=True)
    if errors:
        raise LedgerError("invalid_hatch_v3", "the complete volume outline contract is invalid", {"field": "volume_outline_contract", "errors": errors})
    first, seed = volumes["vol-0001"], _object(manifest.get("step5_volume1"))
    for field in ("title", "spine", "word_budget", "chapters_budget"):
        if first.get(field) != seed.get(field):
            _v3_error(f"step5_volume1.{field}", "must match the already-signed first volume outline")
    if first.get("next_handoff") != seed.get("next_volume_hook"):
        _v3_error("step5_volume1.next_volume_hook", "must match the signed first volume next_handoff")
    return volumes, signed


def assemble_plan_from_manifest(manifest: dict[str, Any]) -> dict[str, Any]:
    """Assemble complete plan JSON structure from manifest."""
    title = manifest.get("title") or "未定名"
    protagonist = _get_protagonist(manifest)
    book_words = manifest.get("book_words") or 2000000

    step4 = _object(manifest.get("step4_outline"))
    step5 = _object(manifest.get("step5_volume1"))
    step6 = _object(manifest.get("step6_beats"))

    volume1_spine = step5.get("spine") or "未设定"
    chapter_words_target = _hatch_chapter_target()
    total_chapters = max(
        len(step6.get("chapters") or manifest.get("chapters") or []),
        expected_total_chapters(book_words, chapter_words_target),
    )

    chapters = step6.get("chapters") or manifest.get("chapters") or []
    event_spine = copy.deepcopy(step4.get("event_spine") or {})
    acts = step4.get("acts") or []
    first_story_stage = str(acts[0].get("name") or "") if acts else ""
    opening_phase = _initial_phase(step4, step5, len(chapters))

    # 规范化 chapters
    norm_chapters = []
    for idx, ch in enumerate(chapters, 1):
        ch_num = ch.get("chapter", idx)
        ch_title = ch.get("title") or f"第{ch_num}章"
        beats = copy.deepcopy(ch.get("beats") or [])
        normalized_chapter = {
            "chapter": ch_num,
            "title": ch_title,
            "beats": beats,
            "phase_id": ch.get("phase_id") or opening_phase["id"],
            "story_stage": ch.get("story_stage") or first_story_stage,
            "thread_refs": copy.deepcopy(
                ch.get("thread_refs") or _opening_chapter_refs(step4, len(norm_chapters), opening_phase)[0]
            ),
            "clock_refs": copy.deepcopy(
                ch.get("clock_refs") or _opening_chapter_refs(step4, len(norm_chapters), opening_phase)[1]
            ),
        }
        # 起手三章同样需要在场者、地点与目标等切片锚。丢掉这些输入会让
        # pack 只认识主角，明明已规划的旧盟友/伏笔场景在正文阶段变成陌生人。
        for key in (
            "location", "present", "tags", "goal", "wound", "speech",
            # 旧 manifest 的 personalities 仅作数据保留；个人表达现在用书级 character_profiles。
            "recap", "kb_refs", "personalities", "knowledge_refs",
        ):
            if key in ch:
                normalized_chapter[key] = copy.deepcopy(ch[key])
        norm_chapters.append(normalized_chapter)

    milestones = step4.get("milestones") or []
    commitments = _normalized_long_term_commitments(step4)
    long_arc = _get_world_mystery(manifest)
    all_volumes, volume_contract = _all_volume_outline_parts(manifest)

    plan: dict[str, Any] = {
        "schema": PLAN_SCHEMA,
        "title": title,
        "protagonist": protagonist,
        "narrative_contract": _narrative_contract_from_manifest(manifest),
        "volume_outline_contract": volume_contract,
        "volume_spine": volume1_spine,
        "book_outline": {
            "book_words": book_words,
            "chapter_words_target": chapter_words_target,
            "total_chapters": total_chapters,
            "acts": acts,
            "milestones": milestones,
            "event_spine": event_spine,
            "volume_outline_schema": VOLUME_OUTLINE_SCHEMA,
            "volume_count": volume_contract["volume_count"],
        },
        "phases": [opening_phase],
        "volumes": all_volumes,
        "chapters": norm_chapters,
    }
    if commitments:
        plan["book_outline"]["long_term_commitments"] = copy.deepcopy(commitments)
    if manifest.get("character_profiles"):
        plan["character_profiles"] = copy.deepcopy(manifest["character_profiles"])
    if long_arc.get("mode") == "present":
        plan["book_outline"]["long_arc_question"] = {
            "core_mystery": long_arc.get("core_mystery") or "",
            "surface_illusion": long_arc.get("surface_illusion") or "",
            "decryption_ladder": copy.deepcopy(long_arc.get("decryption_ladder") or []),
        }
    # 视角结构与平台尺度随 plan 落盘（pack 装配从这里读，写手每章可见）
    for optional_key in ("narrative_pov", "content_fence"):
        if isinstance(manifest.get(optional_key), dict):
            plan[optional_key] = copy.deepcopy(manifest[optional_key])
    return plan


def hatch_project(
    project: Path,
    manifest: dict[str, Any],
) -> dict[str, Any]:
    """Execute complete choice-driven book hatching: validate, write assets, and init project."""
    manifest = validate_hatch_manifest(manifest)
    protagonist = _get_protagonist(manifest)
    book_words = manifest.get("book_words") or 2000000
    voice_id = manifest["voice"]
    background = _text(manifest.get("background"))

    store = BookStore(project)
    if store.head_path.exists():
        raise LedgerError("already_initialized", f"project already has HEAD: {store.head_path}")

    # Validate every deterministic input before creating book/. In particular,
    # an invalid voice id must not leave a half-initialized project behind.
    build_voice_profile(
        voice_id=str(voice_id),
        pack_cap=int(DEFAULT_CONFIG["pack_caps"]["voice_concepts"]),
    )
    background_path = resolve_background(background) if background else None
    plan = assemble_plan_from_manifest(manifest)

    # 1. 确保目录存在
    store.ensure_layout()

    # 2. 写入 intent.md 与 outline.md
    intent_text = render_intent_markdown(manifest)
    atomic_text(store.intent_path, intent_text)

    outline_text = render_outline_markdown(manifest)
    atomic_text(store.outline_path, outline_text)

    # 3. 写入 canon 文件
    canon_files = render_canon_markdowns(manifest)
    for fname, content in canon_files.items():
        atomic_text(store.canon_dir / fname, content)
    background_files = (
        copy_background_canon(background_path, store.canon_dir)
        if background_path is not None
        else []
    )
    plan["narrative_contract"]["source_baselines"] = narrative_contract_source_baselines(store)
    validate_narrative_contract(plan["narrative_contract"])

    # 4. 从 canon 中抽取卡片生成 kb cards
    extracted = extract_cards(store.canon_dir, excerpt_max=0)
    kb_cards = extracted["cards"]

    # 5. 写入组装后的 plan JSON
    temp_plan_path = store.staging_dir / "hatch_plan.json"
    atomic_text(temp_plan_path, json.dumps(plan, ensure_ascii=False, indent=2))

    temp_kb_path = store.staging_dir / "hatch_kb.json"
    atomic_text(temp_kb_path, json.dumps({"cards": kb_cards}, ensure_ascii=False, indent=2))

    # 6. 调用 init_project 完成开书
    init_res = init_project(
        project,
        plan_path=temp_plan_path,
        kb_path=temp_kb_path,
        protagonist=protagonist,
        book_words=book_words,
        voice=voice_id,
    )

    # The confirmed decision trace is the reproducibility/audit source for the
    # generated editorial files. Persist it only after initialization succeeds.
    atomic_text(store.hatch_manifest_path, json.dumps(manifest, ensure_ascii=False, indent=2) + "\n")

    # 7. 回填扩展配置要素（量化口径键与术语表）
    cfg = store.load_config()
    cfg["volume_outline_schema"] = VOLUME_OUTLINE_SCHEMA
    cfg_updated = True
    if "quant_keys" in manifest and isinstance(manifest["quant_keys"], list):
        cfg["quant_keys"] = manifest["quant_keys"]
        cfg_updated = True
    elif "quant_items" in manifest and isinstance(manifest["quant_items"], list):
        keys = []
        for item in manifest["quant_items"]:
            if isinstance(item, dict) and item.get("key"):
                keys.append(str(item["key"]).strip())
            elif isinstance(item, str) and item.strip():
                keys.append(item.strip())
        if keys:
            cfg["quant_keys"] = keys
            cfg_updated = True

    if "glossary" in manifest and isinstance(manifest["glossary"], dict):
        cleaned_glossary = {
            str(k).strip(): str(v).strip()
            for k, v in manifest["glossary"].items()
            if str(k).strip() and str(v).strip() and str(k).strip() != str(v).strip()
        }
        if cleaned_glossary:
            cfg["glossary"] = cleaned_glossary
            cfg_updated = True

    if cfg_updated:
        store.save_config(cfg)

    # 清理临时 staging 文件
    try:
        temp_plan_path.unlink(missing_ok=True)
        temp_kb_path.unlink(missing_ok=True)
    except Exception:
        pass

    return ok(
        action="book_hatch",
        message="choice-driven book hatching completed successfully",
        project=str(project.resolve()),
        protagonist=protagonist,
        name_warnings=protagonist_name_cliche_warnings(protagonist),
        chapters_seeded=len(plan["chapters"]),
        planning_warnings=[
            warning
            for chapter in plan["chapters"]
            for warning in [beats_count_warning(int(chapter["chapter"]), chapter["beats"])]
            if warning
        ],
        schema=manifest.get("schema", "invalid"),
        background=background or None,
        background_files=background_files,
        manifest_path=str(store.hatch_manifest_path),
        init_details=init_res,
    )
